version: "3.9"
services:
    app:
        build:
            context: .
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        networks:
            - buzzvel_network

    mysql:
        image: mysql:8.0
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - buzzvel_network

volumes:
    mysql_data:

networks:
    buzzvel_network:
        driver: bridge
